const {Addition, Subtraction, Multiplication, Division} = require("./Application/Functions/functionsExport")
console.log("hello devops")
console.log("Addition = >" ,Addition(2,3))
console.log("Subtraction = >" ,Subtraction(2,3))
console.log("Multiplication = >" ,Multiplication(2,3))
console.log("Division = >" ,Division(2,3))